language: java
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    secure: dGzZ9hl0ezUCYs72+Z4LUgtny0qsUn3HibpBKo4hriRPMY8EQqaJfi1ZDQTKr3ctjJMtQtcgnlC0BujEV+1W2tObjSJsCAdEbzKYZijwRXSK5jT1sua3EQScKYelpv0z4fd9LIYJJ95xwXMNMmAFSjdu3fRDkxtGgIIKbka8YiE=
deploy:
  provider: releases
  api-key: ${GITHUB_TOKEN}
  file: target/uSkyBlock.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master