language: java
jdk:
- oraclejdk7
- openjdk6
deploy:
  provider: releases
  api_key:
    secure: jwzx6+syioJoymcqS6AmFflOK3mBNFVWg5l215l7nKnaI7RLEVMA5n69s/mShAwmrqCfNg42Erg1p58Eivb2tdughIgWghDUlLXOz+B1KBC107Ci0m5Nvtn2AtXWillwv5KtzbokrfMxrx1mhELXO4h21mWcvAo3ovoB6hZWTII=
  file: target/uSkyBlock.jar
  skip_cleanup: true
  on:
    repo: rlf/uSkyBlock
    all_branches: true
cache:
  directories:
  - $HOME/.m2

