language: java
git:
  submodules: false
deploy:
  provider: releases
  api_key:
    secure: JjpBYKmA8ByMiNEXLQcRyhyvvdgcGw4DR2CYAtusTIYm5cemqHWN9M9kkqGVauOMVONPlxsA8OVRdzPRAAlFY/c9PkCcCspMYSVWs9+Py8sCqMrtTxol3Ncecs1FRItdnFQ4p7x+naTYRZdH0EF+eOfyMAZRq7YY624FX4md3xQ=
  file: target/uSkyBlock.jar
  release-number: latest
  skip_cleanup: true
  on:
    tags: true
    repo: rlf/uSkyBlock
    branch: v2.0.0
    all_branches: true
cache:
  directories:
  - $HOME/.m2