version: '2.0.1 Do not change!'
options:
  general:
    maxPartySize: 4
    worldName: skyworld
    spawnSize: 150
    cooldownInfo: 30
    cooldownRestart: 600
    biomeChange: 3600
  island:
    schematicName: yourschematicname
    distance: 110
    removeCreaturesByTeleport: false
    height: 150
    chestItems: '79:2 360:1 81:1 327:1 40:1 39:1 361:1 338:1 323:1'
    addExtraItems: true
    extraPermissions:
      smallbonus: '4:16 320:5'
      mediumbonus: '50:16 327:1'
      largebonus: '3:5 12:5'
      giantbonus: '2:1 110:1'
      extremebonus: '352:8 263:4'
      donorbonus: '261:1 262:32 272:1'
    worldGuardFlags:
      ALL:
        pvp: 'deny'
        destroy-vehicle: 'deny'
        entity-item-frame-destroy: 'deny'
        entity-painting-destroy: 'deny'
    protectionRange: 105
    allowPvP: deny
    allowIslandLock: true
    useOldIslands: false
    useIslandLevel: true
    useTopTen: true
  extra-menus:
    7:
      title: '§a§lBuy Perks'
      displayItem: CHEST
      commands:
       - 'chestcommands open perks'
      lore:
       - '§fVisit the perk shop to buy'
       - '§fspecial abilities for your'
       - '§fisland and character, as well'
       - '§fas titles and more.'
       - '§e§lClick here to open the shop!'
    16:
      title: '§a§lBuy Donor Perks'
      displayItem: ENDER_CHEST
      commands:
       - '[group.donor]chestcommands open donor'
       - '[!group.donor]donate'
      lore:
       - '§fThis special perk shop is'
       - '§7fonly available to donors!'
       - '[group.donor]§e§lClick here to open the shop!'
       - '[!group.donor]§a§7Click here to become a donor!'
  extras:
    sendToSpawn: false
    obsidianToLava: true
  challenges: 'moved to challenges.yml'
